apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moviebooking-prod
resources:
- ../base
images:
- name: 873961273010.dkr.ecr.ap-south-2.amazonaws.com/moviebooking
  newTag: e53da61
patches:
- path: replica-patch.yaml