apiVersion: v1
kind: ConfigMap
metadata:
  name: moviebooking-config
  # REMOVE namespace from base
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/movie_db"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SERVER_PORT: "8080"